### PR TITLE
ready for pr (i think)

### PR DESCRIPTION
**Pull request by DianomiJH**
We've been using martin's fork for dev work on this, so i copied this over to here. As far as i can tell it's all working swimmingly.

### CODE REVIEW

**Review by mhc-gh — APPROVED** [review]
All good from my perspective

**Review by michael-stevens — CHANGES_REQUESTED** [review]
I don't think the user sync endpoints are right

**Comment by DianomiJH** [comment]
Yeah i'll get those fixed :)

**Comment by DianomiJH** [comment]
@michael-stevens do you know what our userMacro would be? currently we have down "$UID" but it's supposed to be something unique to us according to https://docs.prebid.org/prebid-server/developers/pbs-cookie-sync.html#bidder-instructions-for-building-a-sync-endpoint

**Pull request merged**
